# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ScholarForm AI

[mypy]
python_version = 3.12
ignore_missing_imports = True
follow_imports = skip
files = app
warn_unused_ignores = False
warn_redundant_casts = False
warn_return_any = False
no_implicit_optional = False
