# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ScholarForm AI

target-version = "py312"
line-length = 120

[lint]
select = ["E", "F"]
extend-ignore = ["E501", "F401", "F841"]

[lint.per-file-ignores]
"alembic/versions/*.py" = ["E402", "F401"]
"tests/*.py" = ["E402"]
