// k6 load testing script for AMF API
// Usage:
//   k6 run k6-script.js
//   k6 run --vus 50 --duration 5m k6-script.js
//   k6 run --out csv=results.csv k6-script.js

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

// ------------------------------------------------------------------ //
//  Custom metrics                                                     //
// ------------------------------------------------------------------ //

const formatDuration = new Trend('format_duration_ms');
const validateDuration = new Trend('validate_duration_ms');
const previewDuration = new Trend('preview_duration_ms');
const stylesDuration = new Trend('styles_duration_ms');
const formatSize = new Counter('format_total_bytes');
const errorRate = new Rate('errors');

// ------------------------------------------------------------------ //
//  Configuration                                                      //
// ------------------------------------------------------------------ //

export const options = {
    stages: [
        { duration: '1m', target: 10 },   // ramp-up
        { duration: '3m', target: 50 },   // steady state
        { duration: '1m', target: 100 },  // peak
        { duration: '2m', target: 50 },   // scale down
        { duration: '1m', target: 0 },    // ramp-down
    ],
    thresholds: {
        http_req_duration: ['p(95)<3000'],   // 95% of requests under 3s
        http_req_failed: ['rate<0.05'],      // less than 5% errors
        'format_duration_ms': ['p(95)<5000'],
        'validate_duration_ms': ['p(95)<2000'],
    },
};

// ------------------------------------------------------------------ //
//  Test data                                                          //
// ------------------------------------------------------------------ //

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8000';

const STYLES = ['apa', 'mla', 'chicago', 'ieee', 'harvard', 'vancouver', 'turabian', 'acs', 'ama'];

function makeManuscript() {
    return {
        title: 'k6 Load Test Manuscript',
        authors: [
            { first_name: 'k6', last_name: 'Tester', affiliation: 'Load Test University' },
        ],
        abstract: 'This manuscript is generated by k6 for load testing the AMF API. '.repeat(5),
        keywords: ['k6', 'load', 'test', 'performance'],
        sections: [
            {
                heading: 'Introduction',
                level: 1,
                content: [{ text: 'Introduction paragraph content. '.repeat(30) }],
            },
            {
                heading: 'Methodology',
                level: 1,
                content: [{ text: 'Methodology paragraph content. '.repeat(30) }],
            },
            {
                heading: 'Results',
                level: 1,
                content: [{ text: 'Results paragraph content. '.repeat(30) }],
            },
        ],
        references: [
            {
                authors: [{ first_name: 'k6', last_name: 'Reference' }],
                year: '2024',
                title: 'k6 Load Testing Reference',
                journal: 'Journal of Performance Testing',
                volume: '1',
                issue: '1',
                pages: '1-10',
            },
        ],
    };
}

// ------------------------------------------------------------------ //
//  Main test                                                          //
// ------------------------------------------------------------------ //

export default function () {
    group('Health and Styles', function () {
        // Health check
        let res = http.get(`${BASE_URL}/health`);
        check(res, {
            'health status is 200': (r) => r.status === 200,
            'health response has status field': (r) => r.json('status') !== undefined,
        });
        stylesDuration.add(res.timings.duration);
        errorRate.add(res.status >= 400);
        sleep(1);

        // List styles
        res = http.get(`${BASE_URL}/api/v1/styles`);
        check(res, {
            'styles status is 200': (r) => r.status === 200,
            'styles returns array': (r) => Array.isArray(r.json()),
        });
        stylesDuration.add(res.timings.duration);
        errorRate.add(res.status >= 400);
        sleep(0.5);

        // Get a random style detail
        const styleId = STYLES[Math.floor(Math.random() * STYLES.length)];
        res = http.get(`${BASE_URL}/api/v1/styles/${styleId}`);
        check(res, {
            'style detail status is 200': (r) => r.status === 200,
            'style id matches': (r) => r.json('id') === styleId,
        });
        stylesDuration.add(res.timings.duration);
        errorRate.add(res.status >= 400);
        sleep(0.5);
    });

    group('Validate', function () {
        const ms = makeManuscript();
        const payload = JSON.stringify({ manuscript: ms, style_id: 'apa' });
        const params = { headers: { 'Content-Type': 'application/json' } };

        const res = http.post(`${BASE_URL}/api/v1/validate`, payload, params);
        check(res, {
            'validate status is 200': (r) => r.status === 200,
            'validate has valid field': (r) => r.json('valid') !== undefined,
            'validate has errors field': (r) => Array.isArray(r.json('errors')),
        });
        validateDuration.add(res.timings.duration);
        errorRate.add(res.status >= 400);
        sleep(1);
    });

    group('Format', function () {
        const ms = makeManuscript();
        const payload = JSON.stringify({ manuscript: ms, style_id: 'apa' });
        const params = { headers: { 'Content-Type': 'application/json' } };

        const res = http.post(`${BASE_URL}/api/v1/format`, payload, params);
        check(res, {
            'format status is 200': (r) => r.status === 200,
            'format has download_url': (r) => r.json('download_url') !== undefined,
            'format has pages': (r) => typeof r.json('pages') === 'number',
            'format style_applied is apa': (r) => r.json('style_applied') === 'apa',
        });
        formatDuration.add(res.timings.duration);
        formatSize.add(res.body.length);
        errorRate.add(res.status >= 400);
        sleep(2);
    });

    group('Preview', function () {
        const ms = makeManuscript();
        // Remove references for preview
        delete ms.references;
        const payload = JSON.stringify({ manuscript: ms, style_id: 'mla' });
        const params = { headers: { 'Content-Type': 'application/json' } };

        const res = http.post(`${BASE_URL}/api/v1/preview`, payload, params);
        check(res, {
            'preview status is 200': (r) => r.status === 200,
            'preview returns HTML': (r) => r.json('html') !== undefined,
            'preview contains title': (r) => r.json('html').includes('k6 Load Test Manuscript'),
        });
        previewDuration.add(res.timings.duration);
        errorRate.add(res.status >= 400);
        sleep(1);
    });
}
