# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ScholarForm AI

grobid:
  models:
    - name: "header"
      engine: "delft"
      modelType: "BidLSTM_CRF"
    - name: "citation"
      engine: "delft"
      modelType: "BidLSTM_CRF"

  consolidation:
    service: "disabled"

  nb_threads: 1
  batch_size: 10

