# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ScholarForm AI

blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/rohitkumarnaidu/-Auto-AI-Automated-Academic-Docx-Manuscript-Formatter/discussions
    about: Please ask and answer questions here.
