# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ScholarForm AI

"""add_job_state_columns

Revision ID: 5ab5f4f9e36d
Revises: 530ab1236474
Create Date: 2026-02-08 18:56:34.457632

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ab5f4f9e36d"
down_revision: str | Sequence[str] | None = "530ab1236474"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("institution", sa.String(), nullable=True),
        sa.Column("role", sa.String(), server_default="authenticated", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_email"), "profiles", ["email"], unique=False)
    op.create_index(op.f("ix_profiles_id"), "profiles", ["id"], unique=False)
    op.create_table(
        "document_results",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("structured_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_results_document_id"), "document_results", ["document_id"], unique=False)
    op.create_table(
        "document_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.String(), nullable=False),
        sa.Column("edited_structured_data", sa.JSON(), nullable=True),
        sa.Column("output_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_document_versions_document_id"), "document_versions", ["document_id"], unique=False)
    op.drop_index(op.f("idx_document_version_document_id"), table_name="document_version")
    op.drop_table("document_version")
    op.drop_index(op.f("idx_document_result_document_id"), table_name="document_result")
    op.drop_table("document_result")
    op.add_column("documents", sa.Column("progress", sa.Integer(), nullable=True))
    op.add_column("documents", sa.Column("current_stage", sa.String(), nullable=True))
    op.add_column("documents", sa.Column("error_message", sa.String(), nullable=True))
    op.add_column(
        "documents", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.alter_column("documents", "raw_text", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
    op.drop_index(op.f("idx_documents_created_at"), table_name="documents")
    op.drop_index(op.f("idx_documents_status"), table_name="documents")
    op.drop_index(op.f("idx_documents_user_id"), table_name="documents")
    op.create_index(op.f("ix_documents_user_id"), "documents", ["user_id"], unique=False)
    op.drop_constraint(op.f("documents_user_id_fkey"), "documents", type_="foreignkey")
    op.alter_column("processing_status", "document_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("processing_status", "message", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
    op.drop_index(op.f("idx_processing_status_document_id"), table_name="processing_status")
    op.drop_index(op.f("idx_processing_status_phase"), table_name="processing_status")
    op.create_index(op.f("ix_processing_status_document_id"), "processing_status", ["document_id"], unique=False)
    op.drop_constraint(op.f("processing_status_document_id_fkey"), "processing_status", type_="foreignkey")
    op.create_foreign_key(None, "processing_status", "documents", ["document_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "processing_status", type_="foreignkey")
    op.create_foreign_key(
        op.f("processing_status_document_id_fkey"),
        "processing_status",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_processing_status_document_id"), table_name="processing_status")
    op.create_index(op.f("idx_processing_status_phase"), "processing_status", ["phase"], unique=False)
    op.create_index(op.f("idx_processing_status_document_id"), "processing_status", ["document_id"], unique=False)
    op.alter_column("processing_status", "message", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
    op.alter_column("processing_status", "document_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("documents_user_id_fkey"), "documents", "users", ["user_id"], ["id"], referent_schema="auth"
    )
    op.drop_index(op.f("ix_documents_user_id"), table_name="documents")
    op.create_index(op.f("idx_documents_user_id"), "documents", ["user_id"], unique=False)
    op.create_index(op.f("idx_documents_status"), "documents", ["status"], unique=False)
    op.create_index(op.f("idx_documents_created_at"), "documents", [sa.literal_column("created_at DESC")], unique=False)
    op.alter_column("documents", "raw_text", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
    op.drop_column("documents", "updated_at")
    op.drop_column("documents", "error_message")
    op.drop_column("documents", "current_stage")
    op.drop_column("documents", "progress")
    op.create_table(
        "document_result",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column("document_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("structured_data", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("validation_results", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("document_result_document_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_result_pkey")),
    )
    op.create_index(op.f("idx_document_result_document_id"), "document_result", ["document_id"], unique=False)
    op.create_table(
        "document_version",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), autoincrement=False, nullable=False),
        sa.Column("document_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("version_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "edited_structured_data", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("output_path", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("document_version_document_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_version_pkey")),
    )
    op.create_index(op.f("idx_document_version_document_id"), "document_version", ["document_id"], unique=False)
    op.drop_index(op.f("ix_document_versions_document_id"), table_name="document_versions")
    op.drop_table("document_versions")
    op.drop_index(op.f("ix_document_results_document_id"), table_name="document_results")
    op.drop_table("document_results")
    op.drop_index(op.f("ix_profiles_id"), table_name="profiles")
    op.drop_index(op.f("ix_profiles_email"), table_name="profiles")
    op.drop_table("profiles")
    # ### end Alembic commands ###


__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]
